alias humble='source /opt/ros/humble/setup.bash'
alias cb='colcon build'
alias cbs='colcon build --packages-select'
alias gzs='source /usr/share/gazebo/setup.bash'
alias src='source install/setup.bash'
alias groot='./Groot/build/Groot'
